### ISSUE TITLE
multiple ammo types in stuff

### ISSUE THREAD

**Issue by KorGgenT** [KorGgenT/Cataclysm-DDA#21]
exmple: ecig

**Comment by KorGgenT** [comment]
compressed air crossbow

**Comment by darktoes** [comment]
As far as I know, the main use for this is pneumatic weapons. E.G an air rifle. The player first loads a "compressed air canister" into the gun, which is full of, say, 100 charges of "compressed air". They can then load an "air rifle pellet" or "air rifle magazine" full of "air rifle pellet"s into the gun. Once both are loaded, it can be fired. Firing it costs both 1 "air rifle pellet" and 5 charges of "compressed air". If both run out, it can no longer be fired.

If it's possible, I'd also appreciate it if you could see if you could make gunmods a valid reload location. I was speaking to someone about it on Discord before and it seems the only reason you can't reload from ammo stored in a gunmod is that it doesn't look there. This would be useful for things like a bow-mounted quiver or a rifle sling with a built-in bandolier. In addition, you may need to look at reloading the gunmod while still attached to the gun.
