### ISSUE TITLE
vehicle heaters / air conditioners

### ISSUE THREAD

**Issue by KorGgenT** [KorGgenT/Cataclysm-DDA#4]
like a fire, but using electricity.

**Comment by Phenomphear** [comment]
I guess the first thing that needs to be established is what heat function to use, and then, how much power it should drain. I know most single room heaters that are worth their salt are around 1750 watts. Heaters eat a ton of power to produce heat, so it should be pretty hungry, but, there are also oil based radiators that could consume cooking oil as fuel for the heater.

**Comment by Phenomphear** [comment]
Also, it should prob either be a vehicle part or a construction that way it can be placed.

**Comment by Phenomphear** [comment]
`{
    "type": "vehicle_part",
    "id": "cargo_heater",
    "name": "cargo heater ",
    "symbol": "!",
    "color": "red",
    "broken_symbol": ".",
    "broken_color": "light_gray",
    "damage_modifier": 40,
    "durability": 200,
    "description": "A large heater designed to heat the cargohold of a vehicle to keep personel inside warm. Could be used to heat a small room if mounted to a frame and supplied with enough power.",
    "item": "oven",
    "location": "center",
    "requirements": {
      "install": { "time": 20000, "skills": [ [ "mechanics", 4 ] ], "qualities": [ { "id": "WRENCH", "level": 2 } ] },
      "repair": { "skills": [ [ "mechanics", 4 ] ], "time": 2000, "using": [ [ "welding_standard", 5 ] ] },
      "removal": { "skills": [ [ "mechanics", 2 ] ], "qualities": [ { "id": "WRENCH", "level": 2 } ] }
    },
    "flags": [  ],
    "breaks_into": [ { "item": "oven", "count": [ 1 ] } ]
  }`

I don't know what flags to give it, but, heres some base item code we can start with.

**Comment by Phenomphear** [comment]
```
{
    "type": "vehicle_part",
    "id": "cargo_heater",
    "name": "cargo heater ",
    "symbol": "!",
    "color": "red",
    "broken_symbol": ".",
    "broken_color": "light_gray",
    "damage_modifier": 40,
    "durability": 200,
    "description": "A large heater designed to heat the cargohold of a vehicle to keep personel inside warm. Could be used to heat a small room if mounted to a frame and supplied with enough power.",
    "item": "oven",
    "location": "center",
    "requirements": {
      "install": { "time": 20000, "skills": [ [ "mechanics", 4 ] ], "qualities": [ { "id": "WRENCH", "level": 2 } ] },
      "repair": { "skills": [ [ "mechanics", 4 ] ], "time": 2000, "using": [ [ "welding_standard", 5 ] ] },
      "removal": { "skills": [ [ "mechanics", 2 ] ], "qualities": [ { "id": "WRENCH", "level": 2 } ] }
    },
    "flags": [  ],
    "breaks_into": [ { "item": "oven", "count": [ 1 ] } ]
  }
```

I don't what flags to give it, but heres some base code to start with.

**Comment by Phenomphear** [comment]
```{
    "type": "vehicle_part",
    "id": "cargo_heater",
    "name": "cargo heater ",
    "symbol": "!",
    "color": "red",
    "broken_symbol": ".",
    "broken_color": "light_gray",
    "damage_modifier": 40,
    "durability": 200,
    "description": "A large heater designed to heat the cargohold of a vehicle to keep personel inside warm. Could be used to heat a small room if mounted to a frame and supplied with enough power.",
	"epower": -1750,
    "item": "oven",
    "location": "center",
    "requirements": {
      "install": { "time": 20000, "skills": [ [ "mechanics", 4 ] ], "qualities": [ { "id": "WRENCH", "level": 2 } ] },
      "repair": { "skills": [ [ "mechanics", 4 ] ], "time": 2000, "using": [ [ "welding_standard", 5 ] ] },
      "removal": { "skills": [ [ "mechanics", 2 ] ], "qualities": [ { "id": "WRENCH", "level": 2 } ] }
    },
    "flags": [ "ENABLED_DRAINS_EPOWER" ],
    "breaks_into": [ { "item": "oven", "count": [ 1 ] } ]
  }```

Here is it with power drain. I'm not sure if -1750 is the correct way to translate a 1750watt heater, but 1750 watts is 1.75kj/s. I'm going to take a break for now, I've had a headache since yesterday and it's killing me.

**Comment by KorGgenT** [comment]
someone else beat me to it lol
