### ISSUE TITLE
Magiclysm: Crash on attempting to study a spell that has already been learned from a book

### ISSUE THREAD

**Issue by anothersimulacrum** [KorGgenT/Cataclysm-DDA#53]
**Describe the bug**  
When I attempt to study a spell that I have already learned, the game crashes.

**To Reproduce**  
1. Start as a "Would-be-Wizard"
2. Activate the spellbook to learn the spell - when prompted on becoming a wizard, select yes
3. Activate the spellbook again and select the same spell
4. The game crashes

**Expected behavior**  
The game does not crash

**Screenshots**  
![error](https://user-images.githubusercontent.com/42699974/57339821-a609d600-7122-11e9-8d6f-a3fd10f7fcc5.png)

**Versions and configuration(please complete the following information):**
 - OS: Arch Linux 5.0.9
 - Game Version: 0.D-2591-gb570d5c264-dirty
 - Graphics version: Tiles
 - Mods loaded: "dda", Magiclysm

**Additional context**  
Savegame: [crash.zip](https://github.com/KorGgenT/Cataclysm-DDA/files/3154917/crash.zip)
Crash log: [crash.log](https://github.com/KorGgenT/Cataclysm-DDA/files/3154918/crash.log)

**Comment by KorGgenT** [comment]
i've been making edits to how spells are stored in code, and i think it might need to be check again.

**Comment by anothersimulacrum** [comment]
Fixed
