### ISSUE TITLE
Improvements to spawn_item spell type

### ISSUE THREAD

**Issue by chaosvolt** [KorGgenT/Cataclysm-DDA#65]
**Is your feature request related to a problem? Please describe.**  
Currently `spawn_item` only works with self as a valid target.

**Describe the solution you'd like**  
My idea was that, first, the desired item could be spawned on the ground at the specified area if ground is a valid target. If self isn't a valid target for it but ground is, then logically targeting yourself could instead place it at your feet.

Secondly one could add the ability to target allies, which (since this entails playing around with items) would by necessity only be valid for NPCs rather than monsters.

**Describe alternatives you've considered**  
Separate function for such? Nothing decent really comes to mind.

**Additional context**  
So far it seems like it *might* be useful for Magic Sign: Overgrowth, though it seems that using it to spawn a fake item with a `drop_action` to automatically use `ARTIFACT` will always trigger it at the player's location, so there goes that bright idea I had.

**Comment by KorGgenT** [comment]
i've been thinking about it, and i decided that spawning an item should always spawn the item at the caster's location. if other effects are desired, those can be different spell effects.
