### ISSUE TITLE
Druid woodbow not shooting

### ISSUE THREAD

**Issue by Ignaramico** [KorGgenT/Cataclysm-DDA#67]
# Description

The "woodbow" item creathed from the nature spell doesnt shoot, only shows the text "you need to reload " on the log window

# Steps To Reproduce

1. Learn nature bow spell.
2. wield it
3. try to fire.

# Expected behavior

bow shooting

**Comment by foulman** [comment]
That's strange. I did have that happening at one point during the creation of the bow, but I tinkered with the flags and it worked fine. I'll look into it, perhaps I uploaded an older version of the file.

**Comment by foulman** [comment]
Got it. You can do a quick fix by deleting this line from the woodbow entry at the bottom of ethereal_items.json:
"ammo": "NULL",

**Comment by KorGgenT** [comment]
this is fixed
