### ISSUE TITLE
AoE of spells vs range of spells revision

### ISSUE THREAD

**Issue by Ignaramico** [KorGgenT/Cataclysm-DDA#68]
**Is your feature request related to a problem? Please describe.**  
At the moment i started with the Druid profession, And i encountered that the spell "vegetative grasp" radius is of 15 and the range is of 10, making onself always inside of the AoE spell radius, so you always end up being hit and slowed by the spell. (i havent checked other spells).
![Screenshot_2](https://user-images.githubusercontent.com/34730575/59819914-7d632780-92ef-11e9-88ae-3e4275893759.jpg)

**Describe the solution you'd like**  
A possible revision of the spells radius and range

**Describe alternatives you've considered**  
Making oneself invulnerable to damaging spells

**Additional context**  
In case this kind of feature is intended, i apologize for the time it took you to read all this, sorry (>.<)

**Comment by foulman** [comment]
Wait, you get slowed by it? The spell is set to not affect the player or NPCs. I just double checked since I wrote it that way. The way it is all around you is intentional, but it should have zero effect on you yourself. This would be a bug.

**Comment by Ignaramico** [comment]
I get damage from it too, but its kind of minimal, like 20 torso damage

**Comment by foulman** [comment]
20 torso damage is quite a bit IMNSHO, and it shouldn't be happening. @KorGgenT you need to take a look at why this stuff is happening.

**Comment by KorGgenT** [comment]
this is fixed
