### ISSUE TITLE
Cant unwield/throw second fleshpuch

### ISSUE THREAD

**Issue by Ignaramico** [KorGgenT/Cataclysm-DDA#69]
# Describe the bug

If you cast flesh pouch twice in a row, the second one gos immediately to your hands, and cant be unwielded "since it part of your flesh" (with the first the same happens but since it goes to worn items (as a backpack) it isnt an issue).
And that makes you unable to cast spells or wield any weapons until it disappears.

# Steps To Reproduce

1. Cast the flesh pouch spell twice in a row
2. check that one is a worn item and the second one is being wielded
3. try to unwield it
4. fail

# Expected behavior
At first i thought i could cast several and them being automatically equipped as a backpack, then i thought they could be unwielded or thrown. 

# Screenshots

![fp](https://user-images.githubusercontent.com/34730575/59970741-5e54d780-9533-11e9-8cfd-b9c56152803d.jpg)

**Comment by KorGgenT** [comment]
that's actually amusingly intentional

**Comment by Ignaramico** [comment]
oh common xD.
Anyways,then i will close this, thanks for your time.
