### ISSUE TITLE
Finger firelight lasts forever if unwielded into inventory

### ISSUE THREAD

**Issue by Lazasar** [KorGgenT/Cataclysm-DDA#72]
Seems to go away when dropped on the floor, but lasts forever if just placed into inventory

**Comment by KorGgenT** [comment]
ok. i think this is a deeper problem with things in the inventory in general, but i will continue to investigate

**Comment by Ignaramico** [comment]
I thought it was intended, since things like magic light, the technomancer weapon/armor and the weapons from the biomancer, have the same behavior if unwielded in inventory

**Comment by KorGgenT** [comment]
it's not intended; but it's a tricky bug to find

**Comment by Ignaramico** [comment]
Just an extra info note, the same happens in the NPC inventory, traded an finger firelight, and has the same effect as if the player was carrying in its inventory
