### ISSUE TITLE
Error report upn reaching cure light wounds leevel 10

### ISSUE THREAD

**Issue by Ignaramico** [KorGgenT/Cataclysm-DDA#73]
# Describe the bug
After reaching lv10 with the cure light wounds of the biomancer spell, after using it the game shows an error report.

# Steps To Reproduce

1. reach lvl 10 in the cure light wounds of the biomancer spell
2. cast it
3. see the report showing

# Screenshots

![Screenshot_3](https://user-images.githubusercontent.com/34730575/60389481-4cb98580-9a87-11e9-99f5-27022fd2db08.jpg)

**Comment by KorGgenT** [comment]
this should be fixed already
