### ISSUE TITLE
Being able to cast spells wielding 1H things

### ISSUE THREAD

**Issue by Ignaramico** [KorGgenT/Cataclysm-DDA#74]
**Is your feature request related to a problem? Please describe.**  
Since the introduction of the encumbrance system for spells (and more importantly the sound of them), i was thinking if its possible to add being able to cast spells with 1H weapons, maybe with some additional cost to mana or turns.

**Describe alternatives you've considered**  
Maybe adding craftable weapons for casting (basic ones, so you can still use martial arts in melee with a weapon) maybe adding options to it to help the casting (like reducing cost of mana or reducing the failure chance)

**Additional context**  
Being honest, is a hassle being suddenly surrounded and having to unequip your weapon to cast phase door, or recasting the bless spell (or if you are hauling lots of things, waiting to the fleshpouch in your hands to dissappear to recast it again twice

**Comment by foulman** [comment]
To be clear, you are NOT intended to be having a 2nd fleshpouch in your hands, that is basically a bug that I discovered myself when I created it. Unfortunately, for the time being, there's no way of stopping the player from acquiring one, but it is not intended, and I consider doing that to be more than a little on the cheaty side. I may look at making a Greater Fleshpouch though, as I get the impression the spell is used a lot and is appreciated.

**Comment by foulman** [comment]
That being said, there were supposed to be some flags in the works for things like spell focus objects that would allow that, and I do support not having to drop whatever you are doing just to cast every spell. Personally, I think it should be more about the difficulty rating of the spell, your experience level with it, and your overall spellcrafting (theory), to me those would be the most determining factors in you being able to cast it one-handed or even with both hands full. I would not expect a master magician to have to wave his hands and chant nearly as much, if at all, as a novice.

**Comment by KorGgenT** [comment]
a flag is basically a boolean, so "not as much" isn't a thing here. it's either true or false. specifically i'll write up something that lets you flag an item as a "focus" -- which allows you to cast spells with it in your hand. but i'm going to hold off on doing anything more complicated, like 1 handed casting until i do some of my other mainline projects that have to do with limbs and such.

**Comment by Ignaramico** [comment]
having the option to mark an item as a focus, even if its just one at a time, is pretty great, not having to lose duration of the spells that work as buff because of reequipping the weapon (like in the case of bless and Grotesque Enhancement)

**Comment by foulman** [comment]
I originally wanted sustainable spells for things like Grotesque Enhancement, a drain on your mana pool as necessary to maintain them for as long as you could, but it hasn't gone that way. 
As far as focuses go, I was hoping for some that might even give you bonuses to spellcraft or spell levels, like the whole harry potter wand thing, or say focuses that might improve one particular school of magic, or even some that are rings or necklaces. I dunno. It'll get there when it gets there.

**Comment by Ignaramico** [comment]
Since there was the addition of the magical focus flag, i dont see a reason to keep this issue open.

Thanks for your hard work (>n.n)>
