### ISSUE TITLE
Finger firelighter doesnt count as fire

### ISSUE THREAD

**Issue by Ignaramico** [KorGgenT/Cataclysm-DDA#75]
# Describe the bug
The Finger firelighter doesnt count as fire for crafting purpouses contrary to its description

# Steps To Reproduce

1. cast the spell Finger firelighter
2. wield it/put it in invetory/throw it
3. go and try to craft something that needs a nearvy fire

# Expected behavior

Finger firelighter counting as a fire for crafting purpouses, and the crafting menu showing the requisite of a nearvy fire in green.

**Comment by foulman** [comment]
No no.. this has the FIRESTARTER flag like a lighter or matches, it's a small flame, you can't cook or do crafting with it, only ignite larger sources of heat, or cigarettes and whatnot. A source of heat for crafting is much greater. this is just called firelighter for that reason.

**Comment by foulman** [comment]
Ah, correction. This does have flags it should not have, that is probably causing the confusion. It should not have FIRE or FLAMING to be what it is supposed to be. I'll see to it they're fixed soon, sorry for the mixup.
Magical sources for cooking and crafting are on the way, however, be patient.
