### ISSUE TITLE
Magical light and finger firelighter last forever on floor

### ISSUE THREAD

**Issue by Ignaramico** [KorGgenT/Cataclysm-DDA#77]
# Describe the bug
Magical light and finger firelighter last forever on floor, as the item duration doesnt decrease.

# Steps To Reproduce

1. learn any of the two spells (Magical light or finger firelighter)
2. cast the spell so the item spawns
3. drop it on the floor
4. wait and check how the item duration doesnt decrease

# Expected behavior
item duration reduced by turn and leading the item to despawn

version: 0.D-5165-g5122325 
build: 9255

**Comment by Ignaramico** [comment]
Made a separate issue aside of issue #72 (Finger firelight lasts forever if unwielded into inventory), since at that time the item did dissappear when on the floor

**Comment by KorGgenT** [comment]
wait, you're saying it broke somehow?

**Comment by Ignaramico** [comment]
yup, havent tried with the other items (like the weapons from biomancer/druid/technomancer, or armor from the technomancer) Those had the same issue as issue #72 but still despawned on the floor

**Comment by Ignaramico** [comment]
Apparently is fixed already, i will leave the close of the issue to your judgement, because of the related issue #32079 on the main code

**Comment by KorGgenT** [comment]
no, the floor part was unrelated to the inventory part, and the *Inventory part* was fixed

**Comment by Ignaramico** [comment]
just checked as of the latest build at the moment of this post, both issues seems to be fixed, the inventory and the floor
