### ISSUE TITLE
Multiple class starting runes at character creation

### ISSUE THREAD

**Issue by Ignaramico** [KorGgenT/Cataclysm-DDA#80]
# Describe the bug

The possiblity to start a new character with the various starting classes runes

# Steps To Reproduce

1. Make a player with a starting magiclysm profession, and reach the part of adding a name (the only last step is to hit enter)
2. Go back (without modyfing anything) and select another magiclysm starting profession
3. Go to the end of the character creaton and start a game, see how you have 2 starting runes

# Expected behavior

Only having 1 starting rune

# Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/34730575/61173529-2c46fc00-a55a-11e9-9808-47877c194f0e.jpg)

**Comment by Ignaramico** [comment]
Forgot to add, you get both of the traits/mutation classes too

![Screenshot_2](https://user-images.githubusercontent.com/34730575/61173557-8f389300-a55a-11e9-8e8d-a73014607b47.jpg)

**Comment by KorGgenT** [comment]
i believe this is fixed
