### ISSUE TITLE
Spellcasting menu does not display radius for ter-transform spells

### ISSUE THREAD

**Issue by chaosvolt** [KorGgenT/Cataclysm-DDA#82]
# Describe the bug

For spells of effect `ter_transform`, the spellcasting menu does not display the current AoE of the effect.

# Steps To Reproduce

1. Gain a spell whose primary effect is a `ter_transform` with AoE (examples include Fungicide and Move Earth in Magiclysm, as well as Consecrate, Overgrowth, and Wall of Force in Arcana).
2. Bind and press spellcasting key.
3. Check for presence of "spell radius" property listed in spell info.

# Expected behavior

Spellcasting menu will display AoE as it would for `target_attack` spells that also use AoE in the same way.

# Screenshots

![image](https://user-images.githubusercontent.com/11582235/65533362-4b470000-deb2-11e9-9ac4-c5557dbfe151.png)

![image](https://user-images.githubusercontent.com/11582235/65535011-754df180-deb5-11e9-8b73-b8cf40aa6d54.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-7902-ga495d62 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm]
]

# Additional context

This was discovered in: https://github.com/chaosvolt/cdda-arcana-mod/issues/84

The attempted workaround led to discovering another, more disruptive bug, report for that will follow shortly.

**Comment by ZhilkinSerg** [comment]
Can be closed now (won't be closed automatically if merger has no rights in this repo).
