### ISSUE TITLE
extra_effects do not respect max_aoe or aoe_increment

### ISSUE THREAD

**Issue by chaosvolt** [KorGgenT/Cataclysm-DDA#83]
# Describe the bug

If a spell of effect `ter_transform` is called as secondary effect via `extra_effects`,  only the minimum AoE will be applied. Maximum AoE and `aoe_increment` do not end up increasing the AoE size, whereas they would if a ter_transform is cast as the primary spell effect.

# Steps To Reproduce

1. Debug in a spell with any AoE effect as an extra_effect (Magiclysm example includes Lightning Storm, Arcana examples include Infernal Flame and Wave of Destruction)
2. Level that spell to maximum.
3. Cast it and note that AoE is limited to their respected minimum AoEs.
4. For comparison, debug in all spells, level "Lightning Blast", "Infernal Flame Corruption", or "Wave of Destruction Pulse" to max level, and cast it directly, observing the AoE.

# Expected behavior

Scaling of AoE will be processed by subspells as it would be for AoE called as a primary spell.

# Screenshots

This was a version of Mark: Drain Life fixed by https://github.com/chaosvolt/cdda-arcana-mod/commit/60ce520f4d950a35d4f913a63b2574ea43165588 before being briefly altered to spawn fields 100% of the time instead of. This was to double-check whether it was ALL AoE subspells or only `ter_transform` ones, and I'm glad I checked:

![image](https://user-images.githubusercontent.com/11582235/65537535-3e2e0f00-deba-11e9-9436-79fc170b7473.png)

For comparison, this is the end result of that same, increased-field-chance version of Drain Life Fatigue, leveled to 10 and cast direcly:

![image](https://user-images.githubusercontent.com/11582235/65537480-25bdf480-deba-11e9-8cf6-95e5b35460a9.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-7902-ga495d62 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Arcana and Magic Items [Arcana]
]

# Additional context

Initially discovered by @Ignaramico and reported here: https://github.com/chaosvolt/cdda-arcana-mod/issues/86 I had a hell of a time sorting out what the actual cause was before I thought to tinker with AoE a bit further, and I was initially convinced that ONLY `ter_transform` was affected, literally at the last minute while opening this issue I thought to test a `target_attack` subspell to see if it acted differently.

**Comment by KorGgenT** [comment]
is it _only_ `ter_furn_transform` that does this?

**Comment by chaosvolt** [comment]
I thought so at first, but then I tested a `target_attack` spell with AoE and found out my initial guess was wrong (Drain Life Fatigue uses target_attack to create fields).

**Comment by KorGgenT** [comment]
fix incoming
