### ISSUE TITLE
relic_data has no documentation

### ISSUE THREAD

**Issue by chaosvolt** [KorGgenT/Cataclysm-DDA#85]
**Is your feature request related to a problem? Please describe.**  
It's difficult to discern what the relic_data feature can do at present. `has`, `condition`, and available `values` are vital to understand in order to utilize the available features.

**Describe the solution you'd like**  
1. List available `has` options. Carry, worn, and wielded I presume exist, but only worn and wielded have any visible implementation, meaning the existence of effects-on-carry is impossible to confirm without source diving.
2. List available `condition` options. `ALWAYS` seems to be the only condition with implementation, leaving what else you can do with it, if any other options exist yet, a complete unknown.
3. List functioning of `values` and other actual effects of relics.

**Describe alternatives you've considered**  
N/A

**Comment by KorGgenT** [comment]
Relic data is partially implemented at this point. I can add a full documentation, but a lot of it will be for features that are not yet implemented. Would this suffice?

**Comment by KorGgenT** [comment]
I can already tell you that there are three possible conditions

**Comment by KorGgenT** [comment]
i think what i'm going to do is open a draft of the documentation; partially because i'm going to write it as if all the features worked. i'll link it here when i do. plus it'll remind me to finish it.

**Comment by chaosvolt** [comment]
That sounds fine, sure. That should save you hassle in the long run, having the documentation as it'll be when the features are finished. Knowing what conditions are currently in also helps, thank you.

Mostly, I'm wondering if always is currently the only valid condition...for example, suppose to wanted hit_you_effect and hit_me_effect only occur a given percent of the time, is that a thing or would it have to be faked via a wonder spell? Here's an example of the workaround I cooked up:
```
    "relic_data": {
      "passive_effects": [
        {
          "has": "WIELD",
          "condition": "ALWAYS",
          "hit_you_effect": [ { "id": "arcana_react_symbol_judgement_wonder" } ]
        }
      ]
    },
```
```
  {
    "type": "SPELL",
    "id": "arcana_react_nothing",
    "name": "React: Nothing",
    "description": "Dirty hack to add RNG to react effects.",
    "valid_targets": [ "none" ],
    "flags": [ "SILENT" ],
    "message": "",
    "effect": "none"
  },
  {
    "type": "SPELL",
    "id": "arcana_react_symbol_judgement_wonder",
    "name": "React: Judgment",
    "description": "Roll for zot!",
    "valid_targets": [ "hostile" ],
    "message": "",
    "effect": "none",
    "flags": [ "WONDER", "SILENT" ],
    "min_damage": 1,
    "max_damage": 1,
    "extra_effects": [
      { "id": "arcana_react_nothing" },
      { "id": "arcana_react_nothing" },
      { "id": "arcana_react_nothing" },
      { "id": "arcana_react_nothing" },
      { "id": "arcana_react_symbol_judgment_zap" }
    ]
  },
  {
    "id": "arcana_react_symbol_judgment_zap",
    "type": "SPELL",
    "name": "React: Electric Sting",
    "description": "Zaps someone in melee.",
    "message": "",
    "flags": [ "SILENT", "RANDOM_DAMAGE", "RANDOM_DURATION" ],
    "valid_targets": [ "hostile" ],
    "effect_str": "zapped",
    "min_range": 1,
    "max_range": 1,
    "effect": "target_attack",
    "min_duration": 100,
    "max_duration": 500,
    "min_damage": 1,
    "max_damage": 3,
    "damage_type": "electric"
  }
```

**Comment by KorGgenT** [comment]
the "condition" is slightly different than what you think it is: it's basically the "environmental" condition. it either is or isn't, it doesn't imply a randomness. if you want something to activate some % of the time you'll need to fake it with the WONDER flag.

**Comment by chaosvolt** [comment]
Ah right, then I'm on the right track at least. Should be...interesting for effects that I intend to only trigger less than 10% of the time, but I can condense that with nested wonders I suspect (much like the concept of faking d100 with a pair of d10s).

**Comment by chaosvolt** [comment]
In the meantime, it looks like the bulk of the relevant info for its current state is entirely within `magic_enchantment.h` it seems? That helps immensely.

**Comment by KorGgenT** [comment]
relic.h technically is what has the actual info, though it has `enchantment`s which are in magic_enchantment.h

**Comment by chaosvolt** [comment]
Ah, nice. Thanks for that. However, now I'm testing a little bug that's seeing me melting in acid and getting shot to ribbons like no tomorrow, issue report will follow shortly...

**Comment by chaosvolt** [comment]
Now that I'm sorting through this...hmm. How all does `u_hit_me work` by the way? Does it only allow spells cast on self, I assume? I'm having trouble getting it to trigger any spells on hit, even when set to hit yourself. For example:
```
  {
    "id": "arcana_react_meteoric_talisman_zap",
    "type": "SPELL",
    "name": "React: Discharge",
    "description": "How about you stop hitting me?",
    "message": "",
    "valid_targets": [ "self", "ground" ],
    "sound_description": "an electric crackle",
    "min_aoe": 2,
    "max_aoe": 2,
    "effect": "target_attack",
    "field_id": "fd_electricity",
    "field_chance": 5,
    "min_field_intensity": 2,
    "max_field_intensity": 2
  }
```

I tried making it give off direct damage and zapping, but that didn't work (it didn't even hit myself with it, even when set to hit self), but neither does field creation.

**Comment by chaosvolt** [comment]
Discovery of the day: on-hit spells trigger even if you miss.

**Comment by foulman** [comment]
LOL, okay now I can't use it until that works.

**Comment by foulman** [comment]
Which sucks because I was looking forward to using that

**Comment by KorGgenT** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/34667
