### ISSUE TITLE
ARMOR_BIO non-functional, only some armor effects protect against status effects

### ISSUE THREAD

**Issue by chaosvolt** [KorGgenT/Cataclysm-DDA#86]
# Describe the bug

Tested adding `ARMOR_ACID`, `ARMOR_CUT`, and `ITEM_ARMOR_ACID` to an item, in all cases there was no evident effect. Stepping in acid would deal damage even with 99 `ARMOR_ACID` or `ITEM_ARMOR_ACID`, bullets would inflict lethal injury even with over a thousand `ARMOR_CUT`, etc.

# Steps To Reproduce

1. Add relic data such as this to an item:
```
    "relic_data": {
      "passive_effects": [
        {
          "has": "WORN",
          "condition": "ALWAYS",
          "values": [
            {
              "value": "ITEM_ARMOR_ACID",
              "add": 99
            }
          ]
        }
      ]
    },
```
2. In above example, wade into acid.
3. Melt.

# Expected behavior

Noticeable reduction of damage in the expected context, especially when armor value being added is high enough that no damage at all is expected.

# Screenshots

![image](https://user-images.githubusercontent.com/11582235/66679147-1fa67280-ec33-11e9-88d3-245ac85ea0ff.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-8418-g126c27b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Arcana and Magic Items [Arcana]
]

# Additional context

Acid and cut were tested in both ARMOR_X and ITEM_ARMOR_X forms. For acid especially, I made sure to test both values both with and without the suit set to cover the feet (after changing the test suit from being wyrmskin/leather to solely leather, as this is how the item normally gets its acid resistance).

For cutting damage tests, an M249 CROWS was used, as ballistic damage is still cutting last I checked. The suit was modified to cover the head, eyes, and mouth due to turrets being magical headshot machines. To further ensure this was the case, I added all six permutations of protection from physical damage:
```
            {
              "value": "ITEM_ARMOR_BASH",
              "add": 99
            },
            {
              "value": "ITEM_ARMOR_CUT",
              "add": 99
            },
            {
              "value": "ITEM_ARMOR_STAB",
              "add": 99
            },
            {
              "value": "ARMOR_BASH",
              "add": 99
            },
            {
              "value": "ARMOR_CUT",
              "add": 99
            },
            {
              "value": "ARMOR_STAB",
              "add": 99
            }
```

THIS time however, the shots reflected off limbs, but headshots still did what seemed to be full damage. I'm now unsure which values work and which don't...

Seeing comments of adding negative values in your mention of tests in https://github.com/CleverRaven/Cataclysm-DDA/pull/34577, I tried that too. No effect was apparent.

Formatting for values were copied from enchanted items in Magiclysm, expanded for clarity.

**Comment by chaosvolt** [comment]
I'm about to re-test with a more idiotproof setup, as I need to better sort out what properties actually work.

**Comment by chaosvolt** [comment]
First proper test, will be using this as my testing device:
```

  {
    "id": "yeet_amulet",
    "copy-from": "holy_symbol",
    "type": "ARMOR",
    "name": "yeet amulet",
    "relic_data": {
      "passive_effects": [
        {
          "has": "WORN",
          "condition": "ALWAYS",
          "values": [
            { "value": "ARMOR_BASH", "add": 1000 },
            { "value": "ARMOR_CUT", "add": 1000 },
            { "value": "ARMOR_STAB", "add": 1000 },
            { "value": "ARMOR_HEAT", "add": 1000 },
            { "value": "ARMOR_COLD", "add": 1000 },
            { "value": "ARMOR_ELEC", "add": 1000 },
            { "value": "ARMOR_ACID", "add": 1000 },
            { "value": "ARMOR_BIO", "add": 1000 }
          ]
        }
      ]
    }
  }
```

I...got one-shot by a hulk. Re-tested with all values lowered to 100. Seems that negative values are how you get protection? Weird, but I'll try negative 100...

Now it seems that bash protection works. Unintuitive, but okay. Next, a rematch with the M249. Seems that okay, this has the expected effect on physical damage types. Time to start testing exotic DTs...electric works. Fire works too, partially. You won't take damage and won't be set on fire, but you will eventually heat up and take damage from blisters. This is reasonable as it still protects from the actual status effect fire itself inflicts.

Alright, I think I've figured out the actual issues:
1. ARMOR_X is more like DAMAGE_TAKEN_X in terms of how
2. Looking at it further, now that I know how it works, it seems the only issue is that acid still applies its secondary effect, and corrosion deals absurd damage very fast. This could be fixed via having acid protection affect application of corrosion like fire protection interacts with being set on fire, or there could be some way to make the damage it deals count as acid damage, so that damage from corrosion will be mitigated by the acid protection.

Blistering counting as heat damage might also be a worthwhile thing to implement too, but this is far less noticeable than what corrosion does.

**Comment by foulman** [comment]
I was pretty sure I explained that negative value part to you last night, didn't I? and Effects aren't stopped.

**Comment by chaosvolt** [comment]
I noticed that now, yeah. Took a moment to sort out.

That said, it stops SOME effects, but not all. Which is...peculiar.

**Comment by chaosvolt** [comment]
That said, now that I've messed with this a bit more, I now know how to work around the few odd parts...

**Comment by KorGgenT** [comment]
to be clear, it only affects things that damage the player via melee_attack. so it will not prevent damage from effects like onfire and corroding

**Comment by chaosvolt** [comment]
Ah, that explains it. Thanks.

**Comment by foulman** [comment]
OH damn, that's right. I guess it won't do much about getting shot by turrets then.

**Comment by chaosvolt** [comment]
Actually that's incorrect, I tested the armor effect and laughed off turrets, at least once I finally got the effect working.

**Comment by foulman** [comment]
Well that's good to know, I didn't get shot by anything, ran into trouble right off the bat.
