### ISSUE TITLE
Casting Shardstorm damages the player character

### ISSUE THREAD

**Issue by mentos046** [KorGgenT/Cataclysm-DDA#91]
# Describe the bug

When casting Shardstorm, the player character is in the area of effect and takes damage.

# Steps To Reproduce

1. Learn the Shardstorm Spell
2. Cast it
3. Take damage

# Expected behavior

The Shardstorm Spell does damage to things adjacent to, but not including, the player character in a distance dependent on it's range stat.

# Screenshots
![a8f651f2d2ad1e6d058cfaba384b4e5b1a46d863](https://user-images.githubusercontent.com/33968650/67610284-44343b80-f757-11e9-9572-530a67ac25a1.jpeg)

![66c15336246a048d577b8bba79ea3346868071d3](https://user-images.githubusercontent.com/33968650/67610294-48605900-f757-11e9-936b-5221e95dfb73.jpeg)

![2cb8930608097431b7efa0603ebdf37276b2880f](https://user-images.githubusercontent.com/33968650/67610297-4eeed080-f757-11e9-84a4-1b8b69b48939.png)

# Versions and configuration

 - OS: Windows 10 64-Bit
 - Game Version:0D-8779-g5ad16b6
 - Graphics version: Tiles
 - Mods loaded:   "dda",
  "more_classes_scenarios",
  "shinigamimod",
  "sleepdeprivation",
  "stats_through_kills",
  "aftershock",
  "crt_expansion",
  "magiclysm",
  "Nechronica_Redux",
  "FIC_Weapons",
  "growable-pots",
  "ew_pack",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "nw_pack",
  "modular_turrets",
  "Salvaged_Robots",
  "hydroponics",
  "Mining_Mod",
  "mutant_npcs",
  "MMA",
  "vamp_stuff",
  "Arcana",
  "vamp_stuff+arcana",
  "more_locations",
  "FujiStruct",
  "Urban_Development",
  "deoxymod",
  "blazemod",
  "Heavy miners",
  "Tanks",
  "sees_player_hitbutton"

# Additional context

None

**Comment by KorGgenT** [comment]
this is not the proper place to post magiclysm bugs. please post them on the main game's repo.
